<?php



namespace App\Controller\Admin;

use App\Entity\JsContent;
use App\Entity\LevelFlag;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\ArrayField;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateTimeField;
use EasyCorp\Bundle\EasyAdminBundle\Field\Field;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;

class LevelFlagCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return LevelFlag::class;
    }

    public function createEntity(string $entityFqcn)
    {
        $levelFlag = new LevelFlag();
        $levelFlag->setJsContent(new JsContent());

        return $levelFlag; // TODO: Change the autogenerated stub
    }

    public function configureFields(string $pageName): iterable
    {
        yield IdField::new('id')
            ->hideOnForm();
        yield Field::new('name');
        yield Field::new('achieveImage');
        yield AssociationField::new('level', 'Level')
            ->autocomplete()
            ->formatValue(function ($value, $entity){
                return $entity->getLevel()->getName();
            });
        yield AssociationField::new('contents')->autocomplete()->hideOnForm();
        yield AssociationField::new('jsContent')->autocomplete()->hideOnForm();

    }
}
