<?php

namespace App\Controller\Admin;

use App\Entity\AchievedFlag;
use App\Entity\Level;
use Doctrine\ORM\EntityManagerInterface;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\ArrayField;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateTimeField;
use EasyCorp\Bundle\EasyAdminBundle\Field\Field;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use Symfony\Component\VarExporter\Exception\NotInstantiableTypeException;

class LevelCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Level::class;
    }

    public function deleteEntity(EntityManagerInterface $entityManager, $entityInstance): void
    {
        if (!$entityInstance instanceof Level)
            throw new NotInstantiableTypeException("Unknown Type of Level!");
        if($entityInstance->getNextLevel() != null)
        {
            $this->addFlash('error', 'This level has the next one. Please, set the next level to null and repeat');
            return;
        }
        $levels = $entityManager->getRepository(Level::class)->findAll();

        foreach ($levels as $level)
        {
            if($level->getNextLevel() === $entityInstance)
            {
                $level->setNextLevel(null);
                $entityManager->persist($level);
                break;
            }
        }
        parent::deleteEntity($entityManager, $entityInstance); // TODO: Change the autogenerated stub
    }

    public function configureFields(string $pageName): iterable
    {
        yield IdField::new('id')
            ->hideOnForm();
        yield Field::new('name', 'Level');
        yield Field::new('url');
        yield AssociationField::new('levelFlags')->autocomplete()->hideOnForm();
        yield AssociationField::new('messages')->autocomplete()->hideOnForm();
        yield AssociationField::new('nextLevel')
            ->autocomplete();

    }
}
